### ISSUE TITLE
Equirectangular projection

### ISSUE THREAD

**Issue by cmbruns-hhmi** [cmbruns/webglobeview#1]
This should be the first projection implemented, because it's so close to the input data

**Comment by cmbruns** [comment]
Fixed in revision https://github.com/cmbruns/webglobeview/commit/3fe01b5bd1469eae1d50fd015178d34e9e33f9be

**Comment by cmbruns** [comment]
Reopening until we can switch between Orthographic and Equirectangular dynamically.

**Comment by cmbruns** [comment]
Fixed in revision https://github.com/cmbruns/webglobeview/commit/76435209d514d13f84868e79ee557eceaa63b9e6
